-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [corpus]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace Corpus

/-- [corpus::adt::Struct]
    Source: 'src/adt.rs', lines 3:0-5:1 -/
structure adt.Struct where
  len : Std.Usize

/-- [corpus::adt::BigStructName]
    Source: 'src/adt.rs', lines 14:0-14:23 -/
@[reducible]
def adt.BigStructName := Unit

/-- [corpus::adt::BigStruct]
    Source: 'src/adt.rs', lines 17:0-24:2 -/
def adt.BigStruct :=
  adt.BigStructName × adt.BigStructName × adt.BigStructName ×
  adt.BigStructName × adt.BigStructName × adt.BigStructName

/-- [corpus::adt_borrows::SharedWrapper]
    Source: 'src/adt_borrows.rs', lines 7:0-7:35 -/
@[reducible]
def adt_borrows.SharedWrapper (T : Type) := T

/-- [corpus::adt_borrows::SharedWrapper1]
    Source: 'src/adt_borrows.rs', lines 26:0-28:1 -/
structure adt_borrows.SharedWrapper1 (T : Type) where
  x : T

/-- [corpus::adt_borrows::SharedWrapper2]
    Source: 'src/adt_borrows.rs', lines 47:0-50:1 -/
structure adt_borrows.SharedWrapper2 (T : Type) where
  x : T
  y : T

/-- [corpus::adt_borrows::MutWrapper]
    Source: 'src/adt_borrows.rs', lines 71:0-71:36 -/
@[reducible]
def adt_borrows.MutWrapper (T : Type) := T

/-- [corpus::adt_borrows::MutWrapper1]
    Source: 'src/adt_borrows.rs', lines 99:0-101:1 -/
structure adt_borrows.MutWrapper1 (T : Type) where
  x : T

/-- [corpus::adt_borrows::MutWrapper2]
    Source: 'src/adt_borrows.rs', lines 129:0-132:1 -/
structure adt_borrows.MutWrapper2 (T : Type) where
  x : T
  y : T

/-- [corpus::adt_borrows::SharedList]
    Source: 'src/adt_borrows.rs', lines 207:0-210:1 -/
@[discriminant isize]
inductive adt_borrows.SharedList (T : Type) where
| Nil : adt_borrows.SharedList T
| Cons : T → adt_borrows.SharedList T → adt_borrows.SharedList T

/-- [corpus::adt_borrows::MutList]
    Source: 'src/adt_borrows.rs', lines 227:0-230:1 -/
@[discriminant isize]
inductive adt_borrows.MutList (T : Type) where
| Nil : adt_borrows.MutList T
| Cons : T → adt_borrows.MutList T → adt_borrows.MutList T

/-- [corpus::arrays::AB]
    Source: 'src/arrays.rs', lines 4:0-7:1
    Visibility: public -/
@[discriminant isize]
inductive arrays.AB where
| A : arrays.AB
| B : arrays.AB

/-- [corpus::arrays::Scalar]
    Source: 'src/arrays.rs', lines 386:0-386:24 -/
@[reducible]
def arrays.Scalar := Array Std.U32 2#usize

/-- [corpus::avl::Ordering]
    Source: 'src/avl.rs', lines 16:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive avl.Ordering where
| Less : avl.Ordering
| Equal : avl.Ordering
| Greater : avl.Ordering

/-- Trait declaration: [corpus::avl::Ord]
    Source: 'src/avl.rs', lines 22:0-24:1
    Visibility: public -/
structure avl.Ord (Self : Type) where
  cmp : Self → Self → Result avl.Ordering

/-- [corpus::avl::Node]
    Source: 'src/avl.rs', lines 26:0-31:1 -/
inductive avl.Node (T : Type) where
| mk :
  T →
  Option (avl.Node T) →
  Option (avl.Node T) →
  Std.I8 →
  avl.Node T

def avl.Node.value {T : Type} (x : avl.Node T) :=
  match x with | avl.Node.mk x1 _ _ _ => x1

def avl.Node.left {T : Type} (x : avl.Node T) :=
  match x with | avl.Node.mk _ x1 _ _ => x1

def avl.Node.right {T : Type} (x : avl.Node T) :=
  match x with | avl.Node.mk _ _ x1 _ => x1

def avl.Node.balance_factor {T : Type} (x : avl.Node T) :=
  match x with | avl.Node.mk _ _ _ x1 => x1

@[simp]
theorem avl.Node.value._simpLemma_ {T : Type} (value : T) (left : Option
  (avl.Node T)) (right : Option (avl.Node T)) (balance_factor : Std.I8) :
  (avl.Node.mk value left right balance_factor).value = value := by rfl

@[simp]
theorem avl.Node.left._simpLemma_ {T : Type} (value : T) (left : Option
  (avl.Node T)) (right : Option (avl.Node T)) (balance_factor : Std.I8) :
  (avl.Node.mk value left right balance_factor).left = left := by rfl

@[simp]
theorem avl.Node.right._simpLemma_ {T : Type} (value : T) (left : Option
  (avl.Node T)) (right : Option (avl.Node T)) (balance_factor : Std.I8) :
  (avl.Node.mk value left right balance_factor).right = right := by rfl

@[simp]
theorem avl.Node.balance_factor._simpLemma_ {T : Type} (value : T) (left :
  Option (avl.Node T)) (right : Option (avl.Node T)) (balance_factor : Std.I8)
  :
  (avl.Node.mk value left right balance_factor).balance_factor = balance_factor
  := by rfl

/-- [corpus::avl::Tree]
    Source: 'src/avl.rs', lines 33:0-35:1
    Visibility: public -/
structure avl.Tree (T : Type) where
  root : Option (avl.Node T)

/-- Trait declaration: [corpus::blanket_impl::Trait1]
    Source: 'src/blanket_impl.rs', lines 3:0-3:15 -/
structure blanket_impl.Trait1 (Self : Type) where

/-- Trait declaration: [corpus::blanket_impl::Trait2]
    Source: 'src/blanket_impl.rs', lines 4:0-6:1 -/
structure blanket_impl.Trait2 (Self : Type) where
  foo : Result Unit

/-- [corpus::bst::Ordering]
    Source: 'src/bst.rs', lines 4:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive bst.Ordering where
| Less : bst.Ordering
| Equal : bst.Ordering
| Greater : bst.Ordering

/-- Trait declaration: [corpus::bst::Ord]
    Source: 'src/bst.rs', lines 10:0-12:1 -/
structure bst.Ord (Self : Type) where
  cmp : Self → Self → Result bst.Ordering

/-- [corpus::bst::Node]
    Source: 'src/bst.rs', lines 14:0-18:1 -/
inductive bst.Node (T : Type) where
| mk : T → Option (bst.Node T) → Option (bst.Node T) → bst.Node T

def bst.Node.value {T : Type} (x : bst.Node T) :=
  match x with | bst.Node.mk x1 _ _ => x1

def bst.Node.left {T : Type} (x : bst.Node T) :=
  match x with | bst.Node.mk _ x1 _ => x1

def bst.Node.right {T : Type} (x : bst.Node T) :=
  match x with | bst.Node.mk _ _ x1 => x1

@[simp]
theorem bst.Node.value._simpLemma_ {T : Type} (value : T) (left : Option
  (bst.Node T)) (right : Option (bst.Node T)) :
  (bst.Node.mk value left right).value = value := by rfl

@[simp]
theorem bst.Node.left._simpLemma_ {T : Type} (value : T) (left : Option
  (bst.Node T)) (right : Option (bst.Node T)) :
  (bst.Node.mk value left right).left = left := by rfl

@[simp]
theorem bst.Node.right._simpLemma_ {T : Type} (value : T) (left : Option
  (bst.Node T)) (right : Option (bst.Node T)) :
  (bst.Node.mk value left right).right = right := by rfl

/-- [corpus::bst::TreeSet]
    Source: 'src/bst.rs', lines 22:0-24:1 -/
structure bst.TreeSet (T : Type) where
  root : Option (bst.Node T)

/-- Trait declaration: [corpus::const_shadow::HasConst]
    Source: 'src/const_shadow.rs', lines 11:0-15:1 -/
structure const_shadow.HasConst (Self : Type) (N1 : Std.Usize) where
  N : Result Std.Usize
  get : Self → Result (Array Std.U8 N1)

/-- [corpus::const_shadow::Foo]
    Source: 'src/const_shadow.rs', lines 18:0-18:11 -/
@[reducible]
def const_shadow.Foo := Unit

/-- [corpus::constants::Pair]
    Source: 'src/constants.rs', lines 37:0-40:1
    Visibility: public -/
structure constants.Pair (T1 : Type) (T2 : Type) where
  x : T1
  y : T2

/-- [corpus::constants::Wrap]
    Source: 'src/constants.rs', lines 50:0-52:1
    Visibility: public -/
structure constants.Wrap (T : Type) where
  value : T

/-- [corpus::constants::V]
    Source: 'src/constants.rs', lines 87:0-89:1
    Visibility: public -/
structure constants.V (T : Type) (N : Std.Usize) where
  x : Array T N

/-- [corpus::curve25519::Scalar52]
    Source: 'src/curve25519.rs', lines 6:0-6:34
    Visibility: public -/
@[reducible]
def curve25519.Scalar52 := Array Std.U64 5#usize

/-- Trait declaration: [corpus::defaulted_method::Trait]
    Source: 'src/defaulted_method.rs', lines 2:0-7:1 -/
structure defaulted_method.Trait (Self : Type) where
  provided_method : Self → Result Std.U32
  required_method : Self → Result Std.U32

/-- [corpus::defaulted_method::NoOverride]
    Source: 'src/defaulted_method.rs', lines 9:0-9:18 -/
@[reducible]
def defaulted_method.NoOverride := Unit

/-- [corpus::defaulted_method::YesOverride]
    Source: 'src/defaulted_method.rs', lines 19:0-19:19 -/
@[reducible]
def defaulted_method.YesOverride := Unit

/-- [corpus::demo::CList]
    Source: 'src/demo.rs', lines 34:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive demo.CList (T : Type) where
| CCons : T → demo.CList T → demo.CList T
| CNil : demo.CList T

/-- Trait declaration: [corpus::demo::Counter]
    Source: 'src/demo.rs', lines 97:0-99:1
    Visibility: public -/
structure demo.Counter (Self : Type) where
  incr : Self → Result (Std.Usize × Self)

/-- [corpus::discriminant::EmptyEnum]
    Source: 'src/discriminant.rs', lines 4:0-4:21
    Visibility: public -/
inductive discriminant.EmptyEnum where

/-- [corpus::discriminant::AlertLevel]
    Source: 'src/discriminant.rs', lines 7:0-10:1
    Visibility: public -/
@[discriminant isize]
inductive discriminant.AlertLevel where
| Warning : discriminant.AlertLevel
| Fatal : discriminant.AlertLevel

/-- [corpus::discriminant::AlertLevelU8]
    Source: 'src/discriminant.rs', lines 14:0-17:1
    Visibility: public -/
@[discriminant u8 [1,2]]
inductive discriminant.AlertLevelU8 where
| Warning : discriminant.AlertLevelU8
| Fatal : discriminant.AlertLevelU8

/-- [corpus::dynamic_size::Wrapper]
    Source: 'src/dynamic_size.rs', lines 7:0-9:1
    Visibility: public -/
structure dynamic_size.Wrapper (T : Type) where
  data : T

/-- Trait declaration: [corpus::from_to::From]
    Source: 'src/from_to.rs', lines 3:0-5:1 -/
structure from_to.From (Self : Type) (T : Type) where
  «from» : T → Result Self

/-- Trait declaration: [corpus::from_to::To]
    Source: 'src/from_to.rs', lines 7:0-11:1 -/
structure from_to.To (Self : Type) where
  «to» : forall {T : Type} (FromInst : from_to.From T Self), Self → Result
    T

/-- [corpus::glue::dead::Unused]
    Source: 'src/glue/dead.rs', lines 3:0-6:1
    Visibility: public -/
structure glue.dead.Unused where
  a : Std.U32
  b : Bool

/-- [corpus::glue::dispatch::Celsius]
    Source: 'src/glue/dispatch.rs', lines 7:0-7:28
    Visibility: public -/
@[reducible]
def glue.dispatch.Celsius := Std.U32

/-- [corpus::glue::dispatch::Label]
    Source: 'src/glue/dispatch.rs', lines 8:0-8:27
    Visibility: public -/
@[reducible]
def glue.dispatch.Label := Bool

/-- Trait declaration: [corpus::traits::GetTrait]
    Source: 'src/traits.rs', lines 301:0-304:1
    Visibility: public -/
structure traits.GetTrait (Self : Type) (Self_W : Type) where
  get_w : Self → Result Self_W

/-- [corpus::glue::dispatch::Ticker]
    Source: 'src/glue/dispatch.rs', lines 32:0-34:1
    Visibility: public -/
structure glue.dispatch.Ticker where
  ticks : Std.Usize

/-- Trait declaration: [corpus::tutorial::Counter]
    Source: 'src/tutorial.rs', lines 106:0-108:1
    Visibility: public -/
structure tutorial.Counter (Self : Type) where
  incr : Self → Result (Std.Usize × Self)

mutual

/-- [corpus::glue::mutual::Tree]
    Source: 'src/glue/mutual.rs', lines 12:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive glue.mutual.Tree where
| Leaf : Std.U32 → glue.mutual.Tree
| Node : Std.U32 → glue.mutual.Forest → glue.mutual.Tree

/-- [corpus::glue::mutual::Forest]
    Source: 'src/glue/mutual.rs', lines 17:0-20:1
    Visibility: public -/
@[discriminant isize]
inductive glue.mutual.Forest where
| Nil : glue.mutual.Forest
| Cons : glue.mutual.Tree → glue.mutual.Forest → glue.mutual.Forest

end

/-- [corpus::hashmap::AList]
    Source: 'src/hashmap.rs', lines 22:0-25:1
    Visibility: public -/
@[discriminant isize]
inductive hashmap.AList (T : Type) where
| Cons : Std.Usize → T → hashmap.AList T → hashmap.AList T
| Nil : hashmap.AList T

/-- [corpus::hashmap::Fraction]
    Source: 'src/hashmap.rs', lines 38:0-41:1 -/
structure hashmap.Fraction where
  dividend : Std.Usize
  divisor : Std.Usize

/-- [corpus::hashmap::HashMap]
    Source: 'src/hashmap.rs', lines 44:0-56:1
    Visibility: public -/
structure hashmap.HashMap (T : Type) where
  num_entries : Std.Usize
  max_load_factor : hashmap.Fraction
  max_load : Std.Usize
  saturated : Bool
  slots : alloc.vec.Vec (hashmap.AList T)

/-- Trait declaration: [corpus::higher_ranked_trait_bounds::RefTrait]
    Source: 'src/higher_ranked_trait_bounds.rs', lines 4:0-6:1 -/
structure higher_ranked_trait_bounds.RefTrait (Self : Type) (X : Type) where
  get : Self → Result X

/-- [corpus::issue_1044_opaque_tuple::GF16]
    Source: 'src/issue_1044_opaque_tuple.rs', lines 5:0-7:1
    Visibility: public -/
structure issue_1044_opaque_tuple.GF16 where
  value : Std.U16

/-- [corpus::issue_134_loop_shared_borrows::AVLNode]
    Source: 'src/issue_134_loop_shared_borrows.rs', lines 3:0-5:1 -/
inductive issue_134_loop_shared_borrows.AVLNode where
| mk :
  Option issue_134_loop_shared_borrows.AVLNode →
  issue_134_loop_shared_borrows.AVLNode

def issue_134_loop_shared_borrows.AVLNode.child (x :
  issue_134_loop_shared_borrows.AVLNode) :=
  match x with | issue_134_loop_shared_borrows.AVLNode.mk x1 => x1

@[simp]
theorem issue_134_loop_shared_borrows.AVLNode.child._simpLemma_ (child : Option
  issue_134_loop_shared_borrows.AVLNode) :
  (issue_134_loop_shared_borrows.AVLNode.mk child).child = child := by rfl

/-- [corpus::issue_134_loop_shared_borrows::AVLTreeSet]
    Source: 'src/issue_134_loop_shared_borrows.rs', lines 7:0-9:1 -/
structure issue_134_loop_shared_borrows.AVLTreeSet where
  root : Option issue_134_loop_shared_borrows.AVLNode

/-- [corpus::issue_194_recursive_struct_projector::AVLNode]
    Source: 'src/issue_194_recursive_struct_projector.rs', lines 2:0-6:1 -/
inductive issue_194_recursive_struct_projector.AVLNode (T : Type) where
| mk :
  T →
  Option (issue_194_recursive_struct_projector.AVLNode T) →
  Option (issue_194_recursive_struct_projector.AVLNode T) →
  issue_194_recursive_struct_projector.AVLNode T

def issue_194_recursive_struct_projector.AVLNode.value {T : Type} (x :
  issue_194_recursive_struct_projector.AVLNode T) :=
  match x with | issue_194_recursive_struct_projector.AVLNode.mk x1 _ _ => x1

def issue_194_recursive_struct_projector.AVLNode.left {T : Type} (x :
  issue_194_recursive_struct_projector.AVLNode T) :=
  match x with | issue_194_recursive_struct_projector.AVLNode.mk _ x1 _ => x1

def issue_194_recursive_struct_projector.AVLNode.right {T : Type} (x :
  issue_194_recursive_struct_projector.AVLNode T) :=
  match x with | issue_194_recursive_struct_projector.AVLNode.mk _ _ x1 => x1

@[simp]
theorem issue_194_recursive_struct_projector.AVLNode.value._simpLemma_ {T :
  Type} (value : T) (left : Option
  (issue_194_recursive_struct_projector.AVLNode T)) (right : Option
  (issue_194_recursive_struct_projector.AVLNode T)) :
  (issue_194_recursive_struct_projector.AVLNode.mk
    value
    left
    right).value
    =
    value := by rfl

@[simp]
theorem issue_194_recursive_struct_projector.AVLNode.left._simpLemma_ {T :
  Type} (value : T) (left : Option
  (issue_194_recursive_struct_projector.AVLNode T)) (right : Option
  (issue_194_recursive_struct_projector.AVLNode T)) :
  (issue_194_recursive_struct_projector.AVLNode.mk
    value
    left
    right).left
    =
    left := by rfl

@[simp]
theorem issue_194_recursive_struct_projector.AVLNode.right._simpLemma_ {T :
  Type} (value : T) (left : Option
  (issue_194_recursive_struct_projector.AVLNode T)) (right : Option
  (issue_194_recursive_struct_projector.AVLNode T)) :
  (issue_194_recursive_struct_projector.AVLNode.mk
    value
    left
    right).right
    =
    right := by rfl

/-- [corpus::issue_270_loop_list::List]
    Source: 'src/issue_270_loop_list.rs', lines 2:0-5:1
    Visibility: public -/
@[discriminant isize]
inductive issue_270_loop_list.List (T : Type) where
| Cons : T → issue_270_loop_list.List T → issue_270_loop_list.List T
| Nil : issue_270_loop_list.List T

/-- [corpus::issue_440_type_error::PeanoNum]
    Source: 'src/issue_440_type_error.rs', lines 3:0-6:1 -/
@[discriminant isize]
inductive issue_440_type_error.PeanoNum where
| Zero : issue_440_type_error.PeanoNum
| Succ : issue_440_type_error.PeanoNum → issue_440_type_error.PeanoNum

/-- [corpus::issue_789_loop_ctx_match::S]
    Source: 'src/issue_789_loop_ctx_match.rs', lines 4:0-7:1
    Visibility: public -/
structure issue_789_loop_ctx_match.S where
  x : Std.U8
  y : Array Std.U8 4#usize

/-- Trait declaration: [corpus::issue_801_hrtb::T]
    Source: 'src/issue_801_hrtb.rs', lines 4:0-6:1 -/
structure issue_801_hrtb.T (Self : Type) (X : Type) where
  dummy : Result X

/-- [corpus::issue_803_self_in_array::Arguments]
    Source: 'src/issue_803_self_in_array.rs', lines 5:0-5:33
    Visibility: public -/
@[reducible]
def issue_803_self_in_array.Arguments := Unit

/-- [corpus::issue_807_missing_symbolic_value::PortableVector]
    Source: 'src/issue_807_missing_symbolic_value.rs', lines 4:0-6:1 -/
structure issue_807_missing_symbolic_value.PortableVector where
  elements : Array Std.U8 16#usize

/-- [corpus::issue_charon_1172::Key]
    Source: 'src/issue_charon_1172.rs', lines 4:0-6:1
    Visibility: public -/
structure issue_charon_1172.Key where
  round_keys : Array (Array Std.U8 16#usize) 29#usize

/-- [corpus::joins::Enum]
    Source: 'src/joins.rs', lines 36:0-40:1 -/
@[discriminant isize]
inductive joins.Enum where
| V0 : joins.Enum
| V1 : joins.Enum
| V2 : joins.Enum

mutual

/-- [corpus::list_borrows::LCell]
    Source: 'src/list_borrows.rs', lines 3:0-6:1
    Visibility: public -/
inductive list_borrows.LCell where
| mk : Std.I32 → list_borrows.List → list_borrows.LCell

/-- [corpus::list_borrows::List]
    Source: 'src/list_borrows.rs', lines 8:0-11:1
    Visibility: public -/
@[discriminant isize]
inductive list_borrows.List where
| Nil : list_borrows.List
| Cons : list_borrows.LCell → list_borrows.List

end

def list_borrows.LCell.value (x : list_borrows.LCell) :=
  match x with | list_borrows.LCell.mk x1 _ => x1

def list_borrows.LCell.next (x : list_borrows.LCell) :=
  match x with | list_borrows.LCell.mk _ x1 => x1

@[simp]
theorem list_borrows.LCell.value._simpLemma_ (value : Std.I32) (next :
  list_borrows.List) : (list_borrows.LCell.mk value next).value = value :=
  by rfl

@[simp]
theorem list_borrows.LCell.next._simpLemma_ (value : Std.I32) (next :
  list_borrows.List) : (list_borrows.LCell.mk value next).next = next := by rfl

/-- [corpus::loop_shared_loan_in_join::State]
    Source: 'src/loop_shared_loan_in_join.rs', lines 16:0-22:1
    Visibility: public -/
structure loop_shared_loan_in_join.State where
  data : Array Std.U64 4#usize
  index : Std.U32
  limit : Std.U32
  padding : Std.U8
  flag : Bool

/-- [corpus::loops::List]
    Source: 'src/loops.rs', lines 80:0-83:1
    Visibility: public -/
@[discriminant isize]
inductive loops.List (T : Type) where
| Cons : T → loops.List T → loops.List T
| Nil : loops.List T

/-- [corpus::loops::issue500_2::A]
    Source: 'src/loops.rs', lines 390:4-390:24 -/
@[reducible]
def loops.issue500_2.A := Array Bool 1#usize

/-- [corpus::loops::issue500_3::A]
    Source: 'src/loops.rs', lines 402:4-402:24 -/
@[reducible]
def loops.issue500_3.A := Array Bool 1#usize

/-- [corpus::loops::AList]
    Source: 'src/loops.rs', lines 506:0-509:1
    Visibility: public -/
@[discriminant isize]
inductive loops.AList (T : Type) where
| Cons : Std.Usize → T → loops.AList T → loops.AList T
| Nil : loops.AList T

/-- [corpus::loops_adts::List]
    Source: 'src/loops_adts.rs', lines 3:0-6:1
    Visibility: public -/
@[discriminant isize]
inductive loops_adts.List (T : Type) where
| Cons : T → loops_adts.List T → loops_adts.List T
| Nil : loops_adts.List T

/-- [corpus::loops_issues::WrapperU32]
    Source: 'src/loops_issues.rs', lines 74:0-76:1 -/
structure loops_issues.WrapperU32 where
  x : Std.U32

/-- [corpus::loops_nested::Key]
    Source: 'src/loops_nested.rs', lines 83:0-86:1 -/
structure loops_nested.Key where
  seed : Array Std.U8 32#usize
  atranspose : Array Std.U16 32#usize

/-- [corpus::loops_nested_rec::Key]
    Source: 'src/loops_nested_rec.rs', lines 83:0-86:1 -/
structure loops_nested_rec.Key where
  seed : Array Std.U8 32#usize
  atranspose : Array Std.U16 32#usize

/-- [corpus::loops_rec::List]
    Source: 'src/loops_rec.rs', lines 81:0-84:1
    Visibility: public -/
@[discriminant isize]
inductive loops_rec.List (T : Type) where
| Cons : T → loops_rec.List T → loops_rec.List T
| Nil : loops_rec.List T

/-- [corpus::loops_rec::issue500_2::A]
    Source: 'src/loops_rec.rs', lines 391:4-391:24 -/
@[reducible]
def loops_rec.issue500_2.A := Array Bool 1#usize

/-- [corpus::loops_rec::issue500_3::A]
    Source: 'src/loops_rec.rs', lines 403:4-403:24 -/
@[reducible]
def loops_rec.issue500_3.A := Array Bool 1#usize

/-- [corpus::loops_rec::AList]
    Source: 'src/loops_rec.rs', lines 507:0-510:1
    Visibility: public -/
@[discriminant isize]
inductive loops_rec.AList (T : Type) where
| Cons : Std.Usize → T → loops_rec.AList T → loops_rec.AList T
| Nil : loops_rec.AList T

/-- [corpus::loops_sequences::Key]
    Source: 'src/loops_sequences.rs', lines 3:0-6:1 -/
structure loops_sequences.Key where
  seed : Array Std.U8 32#usize
  t : Array Std.U16 32#usize

/-- [corpus::mini_tree::Node]
    Source: 'src/mini_tree.rs', lines 3:0-5:1 -/
inductive mini_tree.Node where
| mk : Option mini_tree.Node → mini_tree.Node

def mini_tree.Node.child (x : mini_tree.Node) :=
  match x with | mini_tree.Node.mk x1 => x1

@[simp]
theorem mini_tree.Node.child._simpLemma_ (child : Option mini_tree.Node) :
  (mini_tree.Node.mk child).child = child := by rfl

/-- [corpus::mini_tree::Tree]
    Source: 'src/mini_tree.rs', lines 9:0-11:1 -/
structure mini_tree.Tree where
  root : Option mini_tree.Node

/-- [corpus::names::Struct]
    Source: 'src/names.rs', lines 3:0-5:1 -/
structure names.Struct where
  «name» : String

/-- Trait declaration: [corpus::nested_borrows::Trait1]
    Source: 'src/nested_borrows.rs', lines 4:0-6:1 -/
structure nested_borrows.Trait1 (Self : Type) where
  f : Std.U32 → Result Unit

/-- [corpus::nested_borrows::IterMut]
    Source: 'src/nested_borrows.rs', lines 49:0-51:1 -/
structure nested_borrows.IterMut (T : Type) where
  v : Option T

/-- [corpus::nested_borrows::List]
    Source: 'src/nested_borrows.rs', lines 93:0-96:1 -/
@[discriminant isize]
inductive nested_borrows.List (T : Type) where
| Nil : nested_borrows.List T
| Cons : T → nested_borrows.List T → nested_borrows.List T

/-- [corpus::nested_borrows::ListIterMut]
    Source: 'src/nested_borrows.rs', lines 98:0-100:1 -/
structure nested_borrows.ListIterMut (T : Type) where
  current : Option (nested_borrows.List T)

/-- [corpus::nested_borrows::BitReader]
    Source: 'src/nested_borrows.rs', lines 146:0-149:1
    Visibility: public -/
structure nested_borrows.BitReader where
  data : Slice Std.U8
  bit_buf : Std.U64

/-- [corpus::nested_borrows::MutBorrow]
    Source: 'src/nested_borrows.rs', lines 162:0-164:1
    Visibility: public -/
structure nested_borrows.MutBorrow where
  p : Std.U32

/-- [corpus::no_nested_borrows::Pair]
    Source: 'src/no_nested_borrows.rs', lines 4:0-7:1
    Visibility: public -/
structure no_nested_borrows.Pair (T1 : Type) (T2 : Type) where
  x : T1
  y : T2

/-- [corpus::no_nested_borrows::List]
    Source: 'src/no_nested_borrows.rs', lines 9:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.List (T : Type) where
| Cons : T → no_nested_borrows.List T → no_nested_borrows.List T
| Nil : no_nested_borrows.List T

/-- [corpus::no_nested_borrows::One]
    Source: 'src/no_nested_borrows.rs', lines 20:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.One (T1 : Type) where
| One : T1 → no_nested_borrows.One T1

/-- [corpus::no_nested_borrows::EmptyEnum]
    Source: 'src/no_nested_borrows.rs', lines 26:0-28:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.EmptyEnum where
| Empty : no_nested_borrows.EmptyEnum

/-- [corpus::no_nested_borrows::Enum]
    Source: 'src/no_nested_borrows.rs', lines 32:0-35:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.Enum where
| Variant1 : no_nested_borrows.Enum
| Variant2 : no_nested_borrows.Enum

/-- [corpus::no_nested_borrows::EmptyStruct]
    Source: 'src/no_nested_borrows.rs', lines 39:0-39:25
    Visibility: public -/
@[reducible]
def no_nested_borrows.EmptyStruct := Unit

/-- [corpus::no_nested_borrows::Sum]
    Source: 'src/no_nested_borrows.rs', lines 41:0-44:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.Sum (T1 : Type) (T2 : Type) where
| Left : T1 → no_nested_borrows.Sum T1 T2
| Right : T2 → no_nested_borrows.Sum T1 T2

mutual

/-- [corpus::no_nested_borrows::Tree]
    Source: 'src/no_nested_borrows.rs', lines 218:0-221:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.Tree (T : Type) where
| Leaf : T → no_nested_borrows.Tree T
| Node :
  T →
  no_nested_borrows.NodeElem T →
  no_nested_borrows.Tree T →
  no_nested_borrows.Tree T

/-- [corpus::no_nested_borrows::NodeElem]
    Source: 'src/no_nested_borrows.rs', lines 223:0-226:1
    Visibility: public -/
@[discriminant isize]
inductive no_nested_borrows.NodeElem (T : Type) where
| Cons :
  no_nested_borrows.Tree T →
  no_nested_borrows.NodeElem T →
  no_nested_borrows.NodeElem T
| Nil : no_nested_borrows.NodeElem T

end

/-- [corpus::no_nested_borrows::StructWithTuple]
    Source: 'src/no_nested_borrows.rs', lines 352:0-354:1
    Visibility: public -/
structure no_nested_borrows.StructWithTuple (T1 : Type) (T2 : Type) where
  p : (T1 × T2)

/-- [corpus::no_nested_borrows::StructWithPair]
    Source: 'src/no_nested_borrows.rs', lines 369:0-371:1
    Visibility: public -/
structure no_nested_borrows.StructWithPair (T1 : Type) (T2 : Type) where
  p : no_nested_borrows.Pair T1 T2

/-- [corpus::no_nested_borrows::Tuple]
    Source: 'src/no_nested_borrows.rs', lines 473:0-473:33
    Visibility: public -/
def no_nested_borrows.Tuple (T1 : Type) (T2 : Type) := T1 × T2

/-- [corpus::no_nested_borrows::IdType]
    Source: 'src/no_nested_borrows.rs', lines 496:0-496:24
    Visibility: public -/
@[reducible]
def no_nested_borrows.IdType (T : Type) := T

/-- [corpus::no_nested_borrows::ExpandSimpliy::Wrapper]
    Source: 'src/no_nested_borrows.rs', lines 524:4-524:32
    Visibility: public -/
def no_nested_borrows.ExpandSimpliy.Wrapper (T : Type) := T × T

/-- [corpus::no_nested_borrows::ExpandSimpliy::Wrapper2]
    Source: 'src/no_nested_borrows.rs', lines 534:4-537:5
    Visibility: public -/
structure no_nested_borrows.ExpandSimpliy.Wrapper2 where
  b : Bool
  x : Std.U32

/-- [corpus::order::Wrap]
    Source: 'src/order.rs', lines 22:0-22:21
    Visibility: public -/
@[reducible]
def order.Wrap := Std.U64

/-- [corpus::paper::List]
    Source: 'src/paper.rs', lines 36:0-39:1
    Visibility: public -/
@[discriminant isize]
inductive paper.List (T : Type) where
| Cons : T → paper.List T → paper.List T
| Nil : paper.List T

/-- Trait declaration: [corpus::rename_attribute::BoolTrait]
    Source: 'src/rename_attribute.rs', lines 4:0-14:1
    Visibility: public -/
structure rename_attribute.BoolTest (Self : Type) where
  getTest : Self → Result Bool
  retTest : Self → Result Bool

/-- [corpus::rename_attribute::SimpleEnum]
    Source: 'src/rename_attribute.rs', lines 32:0-37:1 -/
@[discriminant isize]
inductive rename_attribute.VariantsTest where
| Variant1 : rename_attribute.VariantsTest
| SecondVariant : rename_attribute.VariantsTest
| ThirdVariant : rename_attribute.VariantsTest

/-- [corpus::rename_attribute::Foo]
    Source: 'src/rename_attribute.rs', lines 40:0-43:1 -/
structure rename_attribute.StructTest where
  FieldTest : Std.U32

/-- Trait declaration: [corpus::static_items::WithSlice]
    Source: 'src/static_items.rs', lines 3:0-5:1
    Visibility: public -/
structure static_items.WithSlice (Self : Type) where
  SLICE : Result (Slice Std.U16)

/-- Trait declaration: [corpus::traits::BoolTrait]
    Source: 'src/traits.rs', lines 2:0-10:1
    Visibility: public -/
structure traits.BoolTrait (Self : Type) where
  get_bool : Self → Result Bool
  ret_true : Self → Result Bool

/-- Trait declaration: [corpus::traits::ToU64]
    Source: 'src/traits.rs', lines 40:0-42:1
    Visibility: public -/
structure traits.ToU64 (Self : Type) where
  to_u64 : Self → Result Std.U64

/-- [corpus::traits::Wrapper]
    Source: 'src/traits.rs', lines 71:0-73:1
    Visibility: public -/
structure traits.Wrapper (T : Type) where
  x : T

/-- Trait declaration: [corpus::traits::ToType]
    Source: 'src/traits.rs', lines 89:0-91:1
    Visibility: public -/
structure traits.ToType (Self : Type) (T : Type) where
  to_type : Self → Result T

/-- Trait declaration: [corpus::traits::OfType]
    Source: 'src/traits.rs', lines 99:0-103:1
    Visibility: public -/
structure traits.OfType (Self : Type) where
  of_type : forall {T : Type} (ToTypeInst : traits.ToType T Self), T → Result
    Self

/-- Trait declaration: [corpus::traits::OfTypeBis]
    Source: 'src/traits.rs', lines 110:0-117:1
    Visibility: public -/
structure traits.OfTypeBis (Self : Type) (T : Type) where
  ToTypeInst : traits.ToType T Self
  of_type : T → Result Self

/-- [corpus::traits::TestType]
    Source: 'src/traits.rs', lines 123:0-123:26
    Visibility: public -/
@[reducible]
def traits.TestType (T : Type) := T

/-- [corpus::traits::{corpus::traits::TestType<T>}::test::TestType1]
    Source: 'src/traits.rs', lines 128:8-128:30 -/
@[reducible]
def traits.TestType.test.TestType1 := Std.U64

/-- Trait declaration: [corpus::traits::{corpus::traits::TestType<T>}::test::TestTrait]
    Source: 'src/traits.rs', lines 129:8-131:9 -/
structure traits.TestType.test.TestTrait (Self : Type) where
  test : Self → Result Bool

/-- [corpus::traits::BoolWrapper]
    Source: 'src/traits.rs', lines 151:0-151:33
    Visibility: public -/
@[reducible]
def traits.BoolWrapper := Bool

/-- Trait declaration: [corpus::traits::WithConstTy]
    Source: 'src/traits.rs', lines 162:0-173:1
    Visibility: public -/
structure traits.WithConstTy (Self : Type) (Self_V : Type) (Self_W : Type) (LEN
  : Std.Usize) where
  LEN1 : Result Std.Usize
  LEN2 : Result Std.Usize
  ToU64Inst : traits.ToU64 Self_W
  f : Self_W → Array Std.U8 LEN → Result Self_W

/-- Trait declaration: [corpus::traits::ParentTrait0]
    Source: 'src/traits.rs', lines 201:0-205:1
    Visibility: public -/
structure traits.ParentTrait0 (Self : Type) (Self_W : Type) where
  get_name : Self → Result String
  get_w : Self → Result Self_W

/-- Trait declaration: [corpus::traits::ParentTrait1]
    Source: 'src/traits.rs', lines 206:0-206:25
    Visibility: public -/
structure traits.ParentTrait1 (Self : Type) where

/-- Trait declaration: [corpus::traits::ChildTrait]
    Source: 'src/traits.rs', lines 207:0-207:52
    Visibility: public -/
structure traits.ChildTrait (Self : Type) (Self_Clause0_W : Type) where
  ParentTrait0Inst : traits.ParentTrait0 Self Self_Clause0_W
  ParentTrait1Inst : traits.ParentTrait1 Self

/-- Trait declaration: [corpus::traits::ChildTrait1]
    Source: 'src/traits.rs', lines 223:0-223:38
    Visibility: public -/
structure traits.ChildTrait1 (Self : Type) where
  ParentTrait1Inst : traits.ParentTrait1 Self

/-- Trait declaration: [corpus::traits::Iterator]
    Source: 'src/traits.rs', lines 230:0-232:1
    Visibility: public -/
structure traits.Iterator (Self : Type) (Self_Item : Type) where

/-- Trait declaration: [corpus::traits::IntoIterator]
    Source: 'src/traits.rs', lines 234:0-240:1
    Visibility: public -/
structure traits.IntoIterator (Self : Type) (Self_Item : Type) (Self_IntoIter :
  Type) where
  IteratorInst : traits.Iterator Self_IntoIter Self_Item
  into_iter : Self → Result Self_IntoIter

/-- Trait declaration: [corpus::traits::FromResidual]
    Source: 'src/traits.rs', lines 251:0-251:24 -/
structure traits.FromResidual (Self : Type) (T : Type) where

/-- Trait declaration: [corpus::traits::Try]
    Source: 'src/traits.rs', lines 247:0-249:1 -/
structure traits.Try (Self : Type) (Self_Residual : Type) where
  FromResidualInst : traits.FromResidual Self Self_Residual

/-- Trait declaration: [corpus::traits::WithTarget]
    Source: 'src/traits.rs', lines 253:0-255:1
    Visibility: public -/
structure traits.WithTarget (Self : Type) (Self_Target : Type) where

/-- Trait declaration: [corpus::traits::ParentTrait2]
    Source: 'src/traits.rs', lines 257:0-259:1
    Visibility: public -/
structure traits.ParentTrait2 (Self : Type) (Self_U : Type)
  (Self_Clause0_Target : Type) where
  WithTargetInst : traits.WithTarget Self_U Self_Clause0_Target

/-- Trait declaration: [corpus::traits::ChildTrait2]
    Source: 'src/traits.rs', lines 261:0-263:1
    Visibility: public -/
structure traits.ChildTrait2 (Self : Type) (Self_Clause0_U : Type)
  (Self_Clause0_Clause0_Target : Type) where
  ParentTrait2Inst : traits.ParentTrait2 Self Self_Clause0_U
    Self_Clause0_Clause0_Target
  convert : Self_Clause0_U → Result Self_Clause0_Clause0_Target

/-- Trait declaration: [corpus::traits::CFnOnce]
    Source: 'src/traits.rs', lines 287:0-291:1
    Visibility: public -/
structure traits.CFnOnce (Self : Type) (Args : Type) (Self_Output : Type) where
  call_once : Self → Args → Result Self_Output

/-- Trait declaration: [corpus::traits::CFnMut]
    Source: 'src/traits.rs', lines 293:0-295:1
    Visibility: public -/
structure traits.CFnMut (Self : Type) (Args : Type) (Self_Clause0_Output :
  Type) where
  CFnOnceInst : traits.CFnOnce Self Args Self_Clause0_Output
  call_mut : Self → Args → Result (Self_Clause0_Output × Self)

/-- Trait declaration: [corpus::traits::CFn]
    Source: 'src/traits.rs', lines 297:0-299:1
    Visibility: public -/
structure traits.CFn (Self : Type) (Args : Type) (Self_Clause0_Clause0_Output :
  Type) where
  CFnMutInst : traits.CFnMut Self Args Self_Clause0_Clause0_Output
  call : Self → Args → Result Self_Clause0_Clause0_Output

/-- Trait declaration: [corpus::traits::Trait]
    Source: 'src/traits.rs', lines 311:0-313:1
    Visibility: public -/
structure traits.Trait (Self : Type) where
  LEN : Result Std.Usize

/-- [corpus::traits::Foo]
    Source: 'src/traits.rs', lines 327:0-330:1
    Visibility: public -/
structure traits.Foo (T : Type) (U : Type) where
  x : T
  y : U

/-- [corpus::tutorial::CList]
    Source: 'src/tutorial.rs', lines 31:0-34:1
    Visibility: public -/
@[discriminant isize]
inductive tutorial.CList (T : Type) where
| CCons : T → tutorial.CList T → tutorial.CList T
| CNil : tutorial.CList T

/-- Trait declaration: [corpus::tutorial::Hash]
    Source: 'src/tutorial.rs', lines 239:0-241:1 -/
structure tutorial.Hash (Self : Type) where
  hash : Std.U32 → Result Std.U32

end Corpus
