-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_ml_kem]: external functions.
-- Models written for the spec pipeline (see crates/mlkem-lean/README.md).
import Aeneas
import MlKem.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open MlKem

namespace MlKemExt

def allEq {T U : Type} (inst : core.cmp.PartialEq T U) : List T → List U → Result Bool
  | [], [] => ok true
  | x :: xs, y :: ys => do
    let b ← inst.eq x y
    if b then allEq inst xs ys else ok false
  | _, _ => ok false

/-- `k` more elements, starting at index `i`, threading the closure state. -/
def fromFnAux {T F : Type} (inst : core.ops.function.FnMut F Std.Usize T) :
    (k : Nat) → Nat → F → Result { l : List T // l.length = k }
  | 0, _, _ => ok ⟨[], rfl⟩
  | k + 1, i, f => do
    let r ← inst.call_mut f ⟨BitVec.ofNat _ i⟩
    let p ← fromFnAux inst k (i + 1) r.2
    ok ⟨r.1 :: p.val, by simp [p.property]⟩

def mapAux {T F U : Type} (inst : core.ops.function.FnMut F T U) :
    (l : List T) → F → Result { r : List U // r.length = l.length }
  | [], _ => ok ⟨[], rfl⟩
  | x :: xs, f => do
    let r ← inst.call_mut f x
    let p ← mapAux inst xs r.2
    ok ⟨r.1 :: p.val, by simp [p.property]⟩

end MlKemExt


/-- [core::array::equality::{impl core::cmp::PartialEq<&'_0 [U]> for [T; N]}::eq]:
    Source: '/rustc/library/core/src/array/equality.rs', lines 70:4-70:38
    Name pattern: [core::array::equality::{core::cmp::PartialEq<[@T; @N], &'0 [@U]>}::eq]
    Visibility: public -/
@[rust_fun
  "core::array::equality::{core::cmp::PartialEq<[@T; @N], &'0 [@U]>}::eq"]
def Array.Insts.CoreCmpPartialEqShared0Slice.eq
  {T : Type} {U : Type} {N : Std.Usize} (cmpPartialEqInst : core.cmp.PartialEq
  T U) :
  Array T N → Slice U → Result Bool :=
  fun a s => MlKemExt.allEq cmpPartialEqInst a.val s.val

/-- [core::array::iter::{impl core::iter::traits::collect::IntoIterator<T, core::array::iter::IntoIter<T, N>> for [T; N]}::into_iter]:
    Source: '/rustc/library/core/src/array/iter.rs', lines 56:4-56:40
    Name pattern: [core::array::iter::{core::iter::traits::collect::IntoIterator<[@T; @N], @T, core::array::iter::IntoIter<@T, @N>>}::into_iter]
    Visibility: public -/
@[rust_fun
  "core::array::iter::{core::iter::traits::collect::IntoIterator<[@T; @N], @T, core::array::iter::IntoIter<@T, @N>>}::into_iter"]
def Array.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
  {T : Type} {N : Std.Usize} :
  Array T N → Result (core.array.iter.IntoIter T N) :=
  fun a => ok ⟨a.val⟩

/-- [core::array::iter::{impl core::iter::traits::iterator::Iterator<T> for core::array::iter::IntoIter<T, N>}::next]:
    Source: '/rustc/library/core/src/array/iter.rs', lines 242:4-242:44
    Name pattern: [core::array::iter::{core::iter::traits::iterator::Iterator<core::array::iter::IntoIter<@T, @N>, @T>}::next]
    Visibility: public -/
@[rust_fun
  "core::array::iter::{core::iter::traits::iterator::Iterator<core::array::iter::IntoIter<@T, @N>, @T>}::next"]
def core.array.iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next
  {T : Type} {N : Std.Usize} :
  core.array.iter.IntoIter T N → Result ((Option T) ×
    (core.array.iter.IntoIter T N)) :=
  fun it => match it.rest with
  | [] => ok (none, it)
  | x :: xs => ok (some x, ⟨xs⟩)

/-- [core::array::from_fn]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 110:0-112:52
    Name pattern: [core::array::from_fn]
    Visibility: public -/
@[rust_fun "core::array::from_fn"]
def core.array.from_fn
  {T : Type} {F : Type} (N : Std.Usize) (opsfunctionFnMutFTupleUsizeTInst :
  core.ops.function.FnMut F Std.Usize T) :
  F → Result (Array T N) :=
  fun f => do
  let p ← MlKemExt.fromFnAux opsfunctionFnMutFTupleUsizeTInst N.val 0 f
  ok ⟨p.val, p.property⟩

/-- [core::array::{[T; N]}::map]:
    Source: '/rustc/library/core/src/array/mod.rs', lines 592:4-596:28
    Name pattern: [core::array::{[@T; @N]}::map]
    Visibility: public -/
@[rust_fun "core::array::{[@T; @N]}::map"]
def core.array.Array.map
  {T : Type} {F : Type} {U : Type} {N : Std.Usize}
  (opsfunctionFnMutFTupleTUInst : core.ops.function.FnMut F T U) :
  Array T N → F → Result (Array U N) :=
  fun a f => do
  let p ← MlKemExt.mapAux opsfunctionFnMutFTupleTUInst a.val f
  ok ⟨p.val, by rw [p.property]; exact a.property⟩

/-- [core::hint::black_box]:
    Source: '/rustc/library/core/src/hint.rs', lines 490:0-490:40
    Name pattern: [core::hint::black_box]
    Visibility: public -/
@[rust_fun "core::hint::black_box"]
def core.hint.black_box {T : Type} : T → Result T :=
  fun x => ok x

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
def core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F) :=
  fun r o => match r with
  | .Ok t => ok (.Ok t)
  | .Err e => do
    let f ← opsfunctionFnOnceOTupleEFInst.call_once o e
    ok (.Err f)

/-- [libcrux_platform::platform::simd128_support]:
    Source: 'crates/sys/platform/src/lib.rs', lines 59:4-59:36
    Name pattern: [libcrux_platform::platform::simd128_support]
    Visibility: public -/
@[rust_fun "libcrux_platform::platform::simd128_support"]
def libcrux_platform.platform.simd128_support : Result Bool :=
  ok false

/-- [libcrux_platform::platform::simd256_support]:
    Source: 'crates/sys/platform/src/lib.rs', lines 80:4-80:36
    Name pattern: [libcrux_platform::platform::simd256_support]
    Visibility: public -/
@[rust_fun "libcrux_platform::platform::simd256_support"]
def libcrux_platform.platform.simd256_support : Result Bool :=
  ok false

/-- [libcrux_secrets::int::classify_public::{impl libcrux_secrets::traits::Classify<T> for T}::classify]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 21:4-21:26
    Name pattern: [libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Classify<@T, @T>}::classify]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Classify<@T, @T>}::classify"]
def libcrux_secrets.traits.Classify.Blanket.classify
  {T : Type} (traitsScalarInst : libcrux_secrets.traits.Scalar T) :
  T → Result T :=
  fun x => ok x

/-- [libcrux_secrets::int::classify_public::{impl libcrux_secrets::traits::Declassify<T> for T}::declassify]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 31:4-31:28
    Name pattern: [libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Declassify<@T, @T>}::declassify]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Declassify<@T, @T>}::declassify"]
def libcrux_secrets.traits.Declassify.Blanket.declassify
  {T : Type} (traitsScalarInst : libcrux_secrets.traits.Scalar T) :
  T → Result T :=
  fun x => ok x

/-- [libcrux_secrets::int::classify_public::{impl libcrux_secrets::traits::Classify<[T; N]> for [T; N]}::classify]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 61:4-61:31
    Name pattern: [libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Classify<[@T; @N], [@T; @N]>}::classify]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Classify<[@T; @N], [@T; @N]>}::classify"]
def Array.Insts.Libcrux_secretsTraitsClassifyArray.classify
  {T : Type} {N : Std.Usize} (traitsScalarInst : libcrux_secrets.traits.Scalar
  T) :
  Array T N → Result (Array T N) :=
  fun a => ok a

/-- [libcrux_secrets::int::classify_public::{impl libcrux_secrets::traits::Declassify<[T; N]> for [T; N]}::declassify]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 71:4-71:33
    Name pattern: [libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Declassify<[@T; @N], [@T; @N]>}::declassify]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::classify_public::{libcrux_secrets::traits::Declassify<[@T; @N], [@T; @N]>}::declassify"]
def Array.Insts.Libcrux_secretsTraitsDeclassifyArray.declassify
  {T : Type} {N : Std.Usize} (traitsScalarInst : libcrux_secrets.traits.Scalar
  T) :
  Array T N → Result (Array T N) :=
  fun a => ok a

/-- [libcrux_secrets::int::classify_public::{impl libcrux_secrets::traits::ClassifyRef<&'a [T]> for &'a [T]}::classify_ref]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 123:4-123:36
    Name pattern: [libcrux_secrets::int::classify_public::{libcrux_secrets::traits::ClassifyRef<&'a [@T], &'a [@T]>}::classify_ref]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::classify_public::{libcrux_secrets::traits::ClassifyRef<&'a [@T], &'a [@T]>}::classify_ref"]
def
  SharedASlice.Insts.Libcrux_secretsTraitsClassifyRefSharedASlice.classify_ref
  {T : Type} (traitsScalarInst : libcrux_secrets.traits.Scalar T) :
  Slice T → Result (Slice T) :=
  fun s => ok s

/-- [libcrux_secrets::int::classify_public::classify_mut_slice]:
    Source: 'crates/utils/secrets/src/int/classify_public.rs', lines 208:0-208:39
    Name pattern: [libcrux_secrets::int::classify_public::classify_mut_slice]
    Visibility: public -/
@[rust_fun "libcrux_secrets::int::classify_public::classify_mut_slice"]
def libcrux_secrets.int.classify_public.classify_mut_slice
  {T : Type} : T → Result T :=
  fun x => ok x

/-- [libcrux_secrets::int::I16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 28:8-28:34
    Name pattern: [libcrux_secrets::int::I16]
    Visibility: public -/
@[rust_fun "libcrux_secrets::int::I16"]
def libcrux_secrets.int.I16 : Std.I16 → Result Std.I16 :=
  fun x => ok x

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for i16}::as_u8]:
    Source: 'crates/utils/secrets/src/int.rs', lines 71:12-71:32
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_u8]
    Visibility: public -/
@[rust_fun "libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_u8"]
def I16.Insts.Libcrux_secretsIntCastOps.as_u8 : Std.I16 → Result Std.U8 :=
  fun x => ok (IScalar.hcast .U8 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for i16}::as_u16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 79:12-79:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_u16]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_u16"]
def I16.Insts.Libcrux_secretsIntCastOps.as_u16 : Std.I16 → Result Std.U16 :=
  fun x => ok (IScalar.hcast .U16 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for i32}::as_i16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 83:12-83:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<i32>}::as_i16]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<i32>}::as_i16"]
def I32.Insts.Libcrux_secretsIntCastOps.as_i16 : Std.I32 → Result Std.I16 :=
  fun x => ok (IScalar.cast .I16 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u16}::as_i16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 83:12-83:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u16>}::as_i16]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u16>}::as_i16"]
def U16.Insts.Libcrux_secretsIntCastOps.as_i16 : Std.U16 → Result Std.I16 :=
  fun x => ok (UScalar.hcast .I16 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u32}::as_i16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 83:12-83:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_i16]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_i16"]
def U32.Insts.Libcrux_secretsIntCastOps.as_i16 : Std.U32 → Result Std.I16 :=
  fun x => ok (UScalar.hcast .I16 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u8}::as_i16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 83:12-83:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u8>}::as_i16]
    Visibility: public -/
@[rust_fun "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u8>}::as_i16"]
def U8.Insts.Libcrux_secretsIntCastOps.as_i16 : Std.U8 → Result Std.I16 :=
  fun x => ok (UScalar.hcast .I16 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for i16}::as_i16]:
    Source: 'crates/utils/secrets/src/int.rs', lines 83:12-83:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_i16]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_i16"]
def I16.Insts.Libcrux_secretsIntCastOps.as_i16 : Std.I16 → Result Std.I16 :=
  fun x => ok x

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u64}::as_u32]:
    Source: 'crates/utils/secrets/src/int.rs', lines 87:12-87:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u64>}::as_u32]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u64>}::as_u32"]
def U64.Insts.Libcrux_secretsIntCastOps.as_u32 : Std.U64 → Result Std.U32 :=
  fun x => ok (UScalar.cast .U32 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for i16}::as_i32]:
    Source: 'crates/utils/secrets/src/int.rs', lines 91:12-91:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_i32]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<i16>}::as_i32"]
def I16.Insts.Libcrux_secretsIntCastOps.as_i32 : Std.I16 → Result Std.I32 :=
  fun x => ok (IScalar.cast .I32 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u32}::as_i32]:
    Source: 'crates/utils/secrets/src/int.rs', lines 91:12-91:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_i32]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_i32"]
def U32.Insts.Libcrux_secretsIntCastOps.as_i32 : Std.U32 → Result Std.I32 :=
  fun x => ok (UScalar.hcast .I32 x)

/-- [libcrux_secrets::int::{impl libcrux_secrets::int::CastOps for u16}::as_u64]:
    Source: 'crates/utils/secrets/src/int.rs', lines 95:12-95:34
    Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u16>}::as_u64]
    Visibility: public -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u16>}::as_u64"]
def U16.Insts.Libcrux_secretsIntCastOps.as_u64 : Std.U16 → Result Std.U64 :=
  fun x => ok (UScalar.cast .U64 x)

/-- [libcrux_sha3::portable::incremental::shake128_init]:
    Source: 'crates/algorithms/sha3/src/portable/incremental.rs', lines 246:0-246:37
    Name pattern: [libcrux_sha3::portable::incremental::shake128_init]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::incremental::shake128_init"]
def libcrux_sha3.portable.incremental.shake128_init
  : Result libcrux_sha3.portable.KeccakState :=
  fail .panic

/-- [libcrux_sha3::portable::incremental::shake128_absorb_final]:
    Source: 'crates/algorithms/sha3/src/portable/incremental.rs', lines 257:0-257:63
    Name pattern: [libcrux_sha3::portable::incremental::shake128_absorb_final]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::incremental::shake128_absorb_final"]
def libcrux_sha3.portable.incremental.shake128_absorb_final
  :
  libcrux_sha3.portable.KeccakState → Slice Std.U8 → Result
    libcrux_sha3.portable.KeccakState :=
  fun _ _ => fail .panic

/-- [libcrux_sha3::portable::incremental::shake128_squeeze_first_three_blocks]:
    Source: 'crates/algorithms/sha3/src/portable/incremental.rs', lines 268:0-268:80
    Name pattern: [libcrux_sha3::portable::incremental::shake128_squeeze_first_three_blocks]
    Visibility: public -/
@[rust_fun
  "libcrux_sha3::portable::incremental::shake128_squeeze_first_three_blocks"]
def libcrux_sha3.portable.incremental.shake128_squeeze_first_three_blocks
  :
  libcrux_sha3.portable.KeccakState → Slice Std.U8 → Result
    (libcrux_sha3.portable.KeccakState × (Slice Std.U8)) :=
  fun _ _ => fail .panic

/-- [libcrux_sha3::portable::incremental::shake128_squeeze_next_block]:
    Source: 'crates/algorithms/sha3/src/portable/incremental.rs', lines 288:0-288:72
    Name pattern: [libcrux_sha3::portable::incremental::shake128_squeeze_next_block]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::incremental::shake128_squeeze_next_block"]
def libcrux_sha3.portable.incremental.shake128_squeeze_next_block
  :
  libcrux_sha3.portable.KeccakState → Slice Std.U8 → Result
    (libcrux_sha3.portable.KeccakState × (Slice Std.U8)) :=
  fun _ _ => fail .panic

/-- [libcrux_sha3::portable::sha256]:
    Source: 'crates/algorithms/sha3/src/portable.rs', lines 22:0-22:45
    Name pattern: [libcrux_sha3::portable::sha256]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::sha256"]
def libcrux_sha3.portable.sha256
  : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8) :=
  fun _ _ => fail .panic

/-- [libcrux_sha3::portable::sha512]:
    Source: 'crates/algorithms/sha3/src/portable.rs', lines 34:0-34:45
    Name pattern: [libcrux_sha3::portable::sha512]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::sha512"]
def libcrux_sha3.portable.sha512
  : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8) :=
  fun _ _ => fail .panic

/-- [libcrux_sha3::portable::shake256]:
    Source: 'crates/algorithms/sha3/src/portable.rs', lines 46:0-46:47
    Name pattern: [libcrux_sha3::portable::shake256]
    Visibility: public -/
@[rust_fun "libcrux_sha3::portable::shake256"]
def libcrux_sha3.portable.shake256
  : Slice Std.U8 → Slice Std.U8 → Result (Slice Std.U8) :=
  fun _ _ => fail .panic

/-- [libcrux_traits::kem::slice::{impl core::convert::From<libcrux_traits::kem::arrayref::KeyGenError> for libcrux_traits::kem::slice::KeyGenError}::from]:
    Source: 'traits/src/kem/slice.rs', lines 76:4-76:49
    Name pattern: [libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::KeyGenError, libcrux_traits::kem::arrayref::KeyGenError>}::from]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::KeyGenError, libcrux_traits::kem::arrayref::KeyGenError>}::from"]
def
  libcrux_traits.kem.slice.KeyGenError.Insts.CoreConvertFromKeyGenError.from
  :
  libcrux_traits.kem.arrayref.KeyGenError → Result
    libcrux_traits.kem.slice.KeyGenError :=
  fun e => match e with
  | .InvalidRandomness => ok .InvalidRandomness
  | .Unknown => ok .Unknown

/-- [libcrux_traits::kem::slice::{impl core::convert::From<libcrux_traits::kem::arrayref::EncapsError> for libcrux_traits::kem::slice::EncapsError}::from]:
    Source: 'traits/src/kem/slice.rs', lines 85:4-85:49
    Name pattern: [libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::EncapsError, libcrux_traits::kem::arrayref::EncapsError>}::from]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::EncapsError, libcrux_traits::kem::arrayref::EncapsError>}::from"]
def
  libcrux_traits.kem.slice.EncapsError.Insts.CoreConvertFromEncapsError.from
  :
  libcrux_traits.kem.arrayref.EncapsError → Result
    libcrux_traits.kem.slice.EncapsError :=
  fun e => match e with
  | .InvalidEncapsKey => ok .InvalidEncapsKey
  | .InvalidRandomness => ok .InvalidRandomness
  | .Unknown => ok .Unknown

/-- [libcrux_traits::kem::slice::{impl core::convert::From<libcrux_traits::kem::arrayref::DecapsError> for libcrux_traits::kem::slice::DecapsError}::from]:
    Source: 'traits/src/kem/slice.rs', lines 95:4-95:49
    Name pattern: [libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::DecapsError, libcrux_traits::kem::arrayref::DecapsError>}::from]
    Visibility: public -/
@[rust_fun
  "libcrux_traits::kem::slice::{core::convert::From<libcrux_traits::kem::slice::DecapsError, libcrux_traits::kem::arrayref::DecapsError>}::from"]
def
  libcrux_traits.kem.slice.DecapsError.Insts.CoreConvertFromDecapsError.from
  :
  libcrux_traits.kem.arrayref.DecapsError → Result
    libcrux_traits.kem.slice.DecapsError :=
  fun e => match e with
  | .InvalidCiphertext => ok .InvalidCiphertext
  | .InvalidDecapsKey => ok .InvalidDecapsKey
  | .Unknown => ok .Unknown

