-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_ml_kem]: external types.
-- Models written for the spec pipeline.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::array::iter::IntoIter]
    Source: '/rustc/library/core/src/array/iter.rs', lines 20:0-20:38
    Name pattern: [core::array::iter::IntoIter]
    Visibility: public -/
@[rust_type "core::array::iter::IntoIter"]
structure core.array.iter.IntoIter (T : Type) (N : Std.Usize) where
  rest : List T

/-- [libcrux_sha3::portable::KeccakState]
    Source: 'crates/algorithms/sha3/src/portable.rs', lines 10:0-10:22
    Name pattern: [libcrux_sha3::portable::KeccakState]
    Visibility: public -/
@[rust_type "libcrux_sha3::portable::KeccakState"]
structure libcrux_sha3.portable.KeccakState where
  unit : Unit := ()

