-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_ml_kem]: type definitions
import Aeneas
import MlKem.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace MlKem

/-- Trait declaration: [libcrux_secrets::traits::private::Sealed]
    Source: 'crates/utils/secrets/src/traits.rs', lines 125:4-125:20
    Name pattern: [libcrux_secrets::traits::private::Sealed]
    Visibility: public -/
@[rust_trait "libcrux_secrets::traits::private::Sealed"]
structure libcrux_secrets.traits.private.Sealed (Self : Type) where

/-- Trait declaration: [libcrux_secrets::traits::Scalar]
    Source: 'crates/utils/secrets/src/traits.rs', lines 38:0-38:40
    Name pattern: [libcrux_secrets::traits::Scalar]
    Visibility: public -/
@[rust_trait "libcrux_secrets::traits::Scalar"
  (parentClauses := ["coremarkerCopyInst", "privateSealedInst"])]
structure libcrux_secrets.traits.Scalar (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  privateSealedInst : libcrux_secrets.traits.private.Sealed Self

/-- [libcrux_traits::kem::arrayref::DecapsError]
    Source: 'traits/src/kem/arrayref.rs', lines 69:0-69:20
    Name pattern: [libcrux_traits::kem::arrayref::DecapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::DecapsError"]
inductive libcrux_traits.kem.arrayref.DecapsError where
| InvalidCiphertext : libcrux_traits.kem.arrayref.DecapsError
| InvalidDecapsKey : libcrux_traits.kem.arrayref.DecapsError
| Unknown : libcrux_traits.kem.arrayref.DecapsError

/-- [libcrux_traits::kem::arrayref::EncapsError]
    Source: 'traits/src/kem/arrayref.rs', lines 56:0-56:20
    Name pattern: [libcrux_traits::kem::arrayref::EncapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::EncapsError"]
inductive libcrux_traits.kem.arrayref.EncapsError where
| InvalidEncapsKey : libcrux_traits.kem.arrayref.EncapsError
| InvalidRandomness : libcrux_traits.kem.arrayref.EncapsError
| Unknown : libcrux_traits.kem.arrayref.EncapsError

/-- [libcrux_traits::kem::arrayref::KeyGenError]
    Source: 'traits/src/kem/arrayref.rs', lines 46:0-46:20
    Name pattern: [libcrux_traits::kem::arrayref::KeyGenError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::arrayref::KeyGenError"]
inductive libcrux_traits.kem.arrayref.KeyGenError where
| InvalidRandomness : libcrux_traits.kem.arrayref.KeyGenError
| Unknown : libcrux_traits.kem.arrayref.KeyGenError

/-- Trait declaration: [libcrux_traits::kem::arrayref::Kem]
    Source: 'traits/src/kem/arrayref.rs', lines 8:0-15:1
    Name pattern: [libcrux_traits::kem::arrayref::Kem]
    Visibility: public -/
@[rust_trait "libcrux_traits::kem::arrayref::Kem"]
structure libcrux_traits.kem.arrayref.Kem (Self : Type) (EK_LEN : Std.Usize)
  (DK_LEN : Std.Usize) (CT_LEN : Std.Usize) (SS_LEN : Std.Usize)
  (RAND_KEYGEN_LEN : Std.Usize) (RAND_ENCAPS_LEN : Std.Usize) where
  keygen : Array Std.U8 EK_LEN → Array Std.U8 DK_LEN → Array Std.U8
    RAND_KEYGEN_LEN → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.KeyGenError) × (Array Std.U8 EK_LEN) × (Array
    Std.U8 DK_LEN))
  encaps : Array Std.U8 CT_LEN → Array Std.U8 SS_LEN → Array Std.U8 EK_LEN
    → Array Std.U8 RAND_ENCAPS_LEN → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.EncapsError) × (Array Std.U8 CT_LEN) × (Array
    Std.U8 SS_LEN))
  decaps : Array Std.U8 SS_LEN → Array Std.U8 CT_LEN → Array Std.U8 DK_LEN
    → Result ((core.result.Result Unit
    libcrux_traits.kem.arrayref.DecapsError) × (Array Std.U8 SS_LEN))

/-- [libcrux_traits::kem::slice::DecapsError]
    Source: 'traits/src/kem/slice.rs', lines 60:0-60:20
    Name pattern: [libcrux_traits::kem::slice::DecapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::slice::DecapsError"]
inductive libcrux_traits.kem.slice.DecapsError where
| InvalidCiphertext : libcrux_traits.kem.slice.DecapsError
| InvalidDecapsKey : libcrux_traits.kem.slice.DecapsError
| InvalidDecapsKeyLength : libcrux_traits.kem.slice.DecapsError
| InvalidCiphertextLength : libcrux_traits.kem.slice.DecapsError
| InvalidSharedSecretLength : libcrux_traits.kem.slice.DecapsError
| Unknown : libcrux_traits.kem.slice.DecapsError

/-- [libcrux_traits::kem::slice::EncapsError]
    Source: 'traits/src/kem/slice.rs', lines 41:0-41:20
    Name pattern: [libcrux_traits::kem::slice::EncapsError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::slice::EncapsError"]
inductive libcrux_traits.kem.slice.EncapsError where
| InvalidEncapsKey : libcrux_traits.kem.slice.EncapsError
| InvalidRandomness : libcrux_traits.kem.slice.EncapsError
| InvalidRandomnessLength : libcrux_traits.kem.slice.EncapsError
| InvalidEncapsKeyLength : libcrux_traits.kem.slice.EncapsError
| InvalidCiphertextLength : libcrux_traits.kem.slice.EncapsError
| InvalidSharedSecretLength : libcrux_traits.kem.slice.EncapsError
| Unknown : libcrux_traits.kem.slice.EncapsError

/-- [libcrux_traits::kem::slice::KeyGenError]
    Source: 'traits/src/kem/slice.rs', lines 26:0-26:20
    Name pattern: [libcrux_traits::kem::slice::KeyGenError]
    Visibility: public -/
@[discriminant isize, rust_type "libcrux_traits::kem::slice::KeyGenError"]
inductive libcrux_traits.kem.slice.KeyGenError where
| InvalidRandomness : libcrux_traits.kem.slice.KeyGenError
| InvalidRandomnessLength : libcrux_traits.kem.slice.KeyGenError
| InvalidEncapsKeyLength : libcrux_traits.kem.slice.KeyGenError
| InvalidDecapsKeyLength : libcrux_traits.kem.slice.KeyGenError
| Unknown : libcrux_traits.kem.slice.KeyGenError

/-- Trait declaration: [libcrux_traits::kem::slice::Kem]
    Source: 'traits/src/kem/slice.rs', lines 9:0-9:13
    Name pattern: [libcrux_traits::kem::slice::Kem]
    Visibility: public -/
@[rust_trait "libcrux_traits::kem::slice::Kem"]
structure libcrux_traits.kem.slice.Kem (Self : Type) where
  keygen : Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Result
    ((core.result.Result Unit libcrux_traits.kem.slice.KeyGenError) × (Slice
    Std.U8) × (Slice Std.U8))
  encaps : Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Slice Std.U8 →
    Result ((core.result.Result Unit libcrux_traits.kem.slice.EncapsError) ×
    (Slice Std.U8) × (Slice Std.U8))
  decaps : Slice Std.U8 → Slice Std.U8 → Slice Std.U8 → Result
    ((core.result.Result Unit libcrux_traits.kem.slice.DecapsError) × (Slice
    Std.U8))

/-- Trait declaration: [rand_core::TryRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 189:0-189:16
    Name pattern: [rand_core::TryRng]
    Visibility: public -/
@[rust_trait "rand_core::TryRng" (parentClauses := ["coreerrorErrorInst"])]
structure rand_core.TryRng (Self : Type) (Self_Error : Type) where
  coreerrorErrorInst : core.error.Error Self_Error
  try_next_u32 : Self → Result ((core.result.Result Std.U32 Self_Error) ×
    Self)
  try_next_u64 : Self → Result ((core.result.Result Std.U64 Self_Error) ×
    Self)
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    Self_Error) × Self × (Slice Std.U8))

/-- Trait declaration: [rand_core::TryCryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.10.1/src/lib.rs', lines 249:0-249:30
    Name pattern: [rand_core::TryCryptoRng]
    Visibility: public -/
@[rust_trait "rand_core::TryCryptoRng" (parentClauses := ["TryRngInst"])]
structure rand_core.TryCryptoRng (Self : Type) (Self_Clause0_Error : Type)
  where
  TryRngInst : rand_core.TryRng Self Self_Clause0_Error

/-- Trait declaration: [libcrux_ml_kem::hash_functions::Hash]
    Source: 'libcrux-ml-kem/src/hash_functions.rs', lines 27:0-70:1 -/
structure hash_functions.Hash (Self : Type) (K : Std.Usize) where
  G : Slice Std.U8 → Result (Array Std.U8 64#usize)
  H : Slice Std.U8 → Result (Array Std.U8 32#usize)
  PRF : forall (LEN : Std.Usize), Slice Std.U8 → Result (Array Std.U8 LEN)
  PRFxN : forall {LEN : Std.Usize}, Array (Array Std.U8 33#usize) K → Result
    (Array (Array Std.U8 LEN) K)
  shake128_init_absorb_final : Array (Array Std.U8 34#usize) K → Result Self
  shake128_squeeze_first_three_blocks : Self → Result ((Array (Array Std.U8
    504#usize) K) × Self)
  shake128_squeeze_next_block : Self → Result ((Array (Array Std.U8
    168#usize) K) × Self)

/-- [libcrux_ml_kem::hash_functions::portable::PortableHash]
    Source: 'libcrux-ml-kem/src/hash_functions.rs', lines 82:4-84:5 -/
structure hash_functions.portable.PortableHash (K : Std.Usize) where
  shake128_state : Array libcrux_sha3.portable.KeccakState K

/-- Trait declaration: [libcrux_ml_kem::vector::traits::Repr]
    Source: 'libcrux-ml-kem/src/vector/traits.rs', lines 20:0-20:17
    Visibility: public -/
structure vector.traits.Repr (Self : Type) where

/-- Trait declaration: [libcrux_ml_kem::vector::traits::Operations]
    Source: 'libcrux-ml-kem/src/vector/traits.rs', lines 42:0-216:1
    Visibility: public -/
structure vector.traits.Operations (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self
  corecloneCloneInst : core.clone.Clone Self
  ReprInst : vector.traits.Repr Self
  ZERO : Result Self
  from_i16_array : Slice Std.I16 → Result Self
  to_i16_array : Self → Result (Array Std.I16 16#usize)
  from_bytes : Slice Std.U8 → Result Self
  to_bytes : Self → Slice Std.U8 → Result (Slice Std.U8)
  add : Self → Self → Result Self
  sub : Self → Self → Result Self
  multiply_by_constant : Self → Std.I16 → Result Self
  cond_subtract_3329 : Self → Result Self
  barrett_reduce : Self → Result Self
  montgomery_multiply_by_constant : Self → Std.I16 → Result Self
  to_unsigned_representative : Self → Result Self
  compress_1 : Self → Result Self
  compress : forall (COEFFICIENT_BITS : Std.I32), Self → Result Self
  decompress_1 : Self → Result Self
  decompress_ciphertext_coefficient : forall (COEFFICIENT_BITS : Std.I32), Self
    → Result Self
  ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 →
    Result Self
  ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  ntt_layer_3_step : Self → Std.I16 → Result Self
  inv_ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16
    → Result Self
  inv_ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  inv_ntt_layer_3_step : Self → Std.I16 → Result Self
  ntt_multiply : Self → Self → Std.I16 → Std.I16 → Std.I16 → Std.I16
    → Result Self
  serialize_1 : Self → Result (Array Std.U8 2#usize)
  deserialize_1 : Slice Std.U8 → Result Self
  serialize_4 : Self → Result (Array Std.U8 8#usize)
  deserialize_4 : Slice Std.U8 → Result Self
  serialize_5 : Self → Result (Array Std.U8 10#usize)
  deserialize_5 : Slice Std.U8 → Result Self
  serialize_10 : Self → Result (Array Std.U8 20#usize)
  deserialize_10 : Slice Std.U8 → Result Self
  serialize_11 : Self → Result (Array Std.U8 22#usize)
  deserialize_11 : Slice Std.U8 → Result Self
  serialize_12 : Self → Result (Array Std.U8 24#usize)
  deserialize_12 : Slice Std.U8 → Result Self
  rej_sample : Slice Std.U8 → Slice Std.I16 → Result (Std.Usize × (Slice
    Std.I16))

/-- [libcrux_ml_kem::vector::portable::vector_type::PortableVector]
    Source: 'libcrux-ml-kem/src/vector/portable/vector_type.rs', lines 9:0-11:1
    Visibility: public -/
structure vector.portable.vector_type.PortableVector where
  elements : Array Std.I16 16#usize

/-- [libcrux_ml_kem::variant::MlKem]
    Source: 'libcrux-ml-kem/src/variant.rs', lines 70:0-70:26 -/
@[reducible]
def variant.MlKem := Unit

/-- Trait declaration: [libcrux_ml_kem::variant::Variant]
    Source: 'libcrux-ml-kem/src/variant.rs', lines 13:0-28:1 -/
structure variant.Variant (Self : Type) where
  kdf : forall {Hasher : Type} {K : Std.Usize} {CIPHERTEXT_SIZE : Std.Usize}
    (hash_functionsHashInst : hash_functions.Hash Hasher K), Slice Std.U8 →
    Array Std.U8 CIPHERTEXT_SIZE → Result (Array Std.U8 32#usize)
  entropy_preprocess : forall {Hasher : Type} {K : Std.Usize}
    (hash_functionsHashInst : hash_functions.Hash Hasher K), Slice Std.U8 →
    Result (Array Std.U8 32#usize)
  cpa_keygen_seed : forall {Hasher : Type} {K : Std.Usize}
    (hash_functionsHashInst : hash_functions.Hash Hasher K), Slice Std.U8 →
    Result (Array Std.U8 64#usize)

/-- [libcrux_ml_kem::types::MlKemPublicKey]
    Source: 'libcrux-ml-kem/src/types.rs', lines 5:8-7:9
    Visibility: public -/
structure types.MlKemPublicKey (SIZE : Std.Usize) where
  value : Array Std.U8 SIZE

/-- [libcrux_ml_kem::types::MlKemPrivateKey]
    Source: 'libcrux-ml-kem/src/types.rs', lines 5:8-7:9
    Visibility: public -/
structure types.MlKemPrivateKey (SIZE : Std.Usize) where
  value : Array Std.U8 SIZE

/-- [libcrux_ml_kem::types::MlKemKeyPair]
    Source: 'libcrux-ml-kem/src/types.rs', lines 267:0-270:1
    Visibility: public -/
structure types.MlKemKeyPair (PRIVATE_KEY_SIZE : Std.Usize) (PUBLIC_KEY_SIZE :
  Std.Usize) where
  sk : types.MlKemPrivateKey PRIVATE_KEY_SIZE
  pk : types.MlKemPublicKey PUBLIC_KEY_SIZE

/-- [libcrux_ml_kem::polynomial::PolynomialRingElement]
    Source: 'libcrux-ml-kem/src/polynomial.rs', lines 62:0-64:1 -/
structure polynomial.PolynomialRingElement (Vector : Type) where
  coefficients : Array Vector 16#usize

/-- [libcrux_ml_kem::ind_cpa::unpacked::IndCpaPublicKeyUnpacked]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 46:4-50:5 -/
structure ind_cpa.unpacked.IndCpaPublicKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  t_as_ntt : Array (polynomial.PolynomialRingElement Vector) K
  seed_for_A : Array Std.U8 32#usize
  A : Array (Array (polynomial.PolynomialRingElement Vector) K) K

/-- [libcrux_ml_kem::ind_cpa::unpacked::IndCpaPrivateKeyUnpacked]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 32:4-34:5 -/
structure ind_cpa.unpacked.IndCpaPrivateKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  secret_as_ntt : Array (polynomial.PolynomialRingElement Vector) K

/-- [libcrux_ml_kem::sampling::sample_from_xof::closure]
    Source: 'libcrux-ml-kem/src/sampling.rs', lines 104:12-104:75 -/
@[reducible]
def sampling.sample_from_xof.closure (Vector : Type) (Hasher : Type) (K :
  Std.Usize) :=
Unit

/-- [libcrux_ml_kem::ind_cpa::generate_keypair_unpacked::closure]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 508:35-508:79 -/
@[reducible]
def ind_cpa.generate_keypair_unpacked.closure (Vector : Type) (Hasher : Type)
  (Scheme : Type) (K : Std.Usize) (ETA1 : Std.Usize) (ETA1_RANDOMNESS_SIZE :
  Std.Usize) :=
Unit

/-- [libcrux_ml_kem::serialize::deserialize_ring_elements_reduced_out::closure]
    Source: 'libcrux-ml-kem/src/serialize.rs', lines 154:51-154:95 -/
@[reducible]
def serialize.deserialize_ring_elements_reduced_out.closure (Vector : Type) (K
  : Std.Usize) :=
Unit

/-- [libcrux_ml_kem::types::MlKemCiphertext]
    Source: 'libcrux-ml-kem/src/types.rs', lines 5:8-7:9
    Visibility: public -/
structure types.MlKemCiphertext (SIZE : Std.Usize) where
  value : Array Std.U8 SIZE

/-- [libcrux_ml_kem::matrix::compute_vector_u::closure]
    Source: 'libcrux-ml-kem/src/matrix.rs', lines 132:42-132:86 -/
@[reducible]
def matrix.compute_vector_u.closure (Vector : Type) (K : Std.Usize) := Unit

/-- [libcrux_ml_kem::ind_cpa::encrypt_c1::closure#1]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 818:30-818:74 -/
@[reducible]
def ind_cpa.encrypt_c1.closure_1 (Vector : Type) (Hasher : Type) (K :
  Std.Usize) (C1_LEN : Std.Usize) (U_COMPRESSION_FACTOR : Std.Usize) (BLOCK_LEN
  : Std.Usize) (ETA1 : Std.Usize) (ETA1_RANDOMNESS_SIZE : Std.Usize) (ETA2 :
  Std.Usize) (ETA2_RANDOMNESS_SIZE : Std.Usize) :=
Unit

/-- [libcrux_ml_kem::ind_cpa::encrypt_c1::closure]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 802:31-802:75 -/
@[reducible]
def ind_cpa.encrypt_c1.closure (Vector : Type) (Hasher : Type) (K : Std.Usize)
  (C1_LEN : Std.Usize) (U_COMPRESSION_FACTOR : Std.Usize) (BLOCK_LEN :
  Std.Usize) (ETA1 : Std.Usize) (ETA1_RANDOMNESS_SIZE : Std.Usize) (ETA2 :
  Std.Usize) (ETA2_RANDOMNESS_SIZE : Std.Usize) :=
Unit

/-- [libcrux_ml_kem::ind_cpa::decrypt::closure]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 1173:31-1173:74 -/
@[reducible]
def ind_cpa.decrypt.closure (Vector : Type) (K : Std.Usize) (CIPHERTEXT_SIZE :
  Std.Usize) (VECTOR_U_ENCODED_SIZE : Std.Usize) (U_COMPRESSION_FACTOR :
  Std.Usize) (V_COMPRESSION_FACTOR : Std.Usize) :=
Unit

/-- [libcrux_ml_kem::ind_cpa::deserialize_then_decompress_u::closure]
    Source: 'libcrux-ml-kem/src/ind_cpa.rs', lines 1025:31-1025:74 -/
@[reducible]
def ind_cpa.deserialize_then_decompress_u.closure (Vector : Type) (K :
  Std.Usize) (CIPHERTEXT_SIZE : Std.Usize) (U_COMPRESSION_FACTOR : Std.Usize)
  :=
Unit

/-- [libcrux_ml_kem::ind_cca::unpacked::MlKemPublicKeyUnpacked]
    Source: 'libcrux-ml-kem/src/ind_cca.rs', lines 485:4-488:5
    Visibility: public -/
structure ind_cca.unpacked.MlKemPublicKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  ind_cpa_public_key : ind_cpa.unpacked.IndCpaPublicKeyUnpacked Vector K
  public_key_hash : Array Std.U8 32#usize

/-- [libcrux_ml_kem::ind_cca::unpacked::MlKemPrivateKeyUnpacked]
    Source: 'libcrux-ml-kem/src/ind_cca.rs', lines 478:4-481:5
    Visibility: public -/
structure ind_cca.unpacked.MlKemPrivateKeyUnpacked (Vector : Type) (K :
  Std.Usize) where
  ind_cpa_private_key : ind_cpa.unpacked.IndCpaPrivateKeyUnpacked Vector K
  implicit_rejection_value : Array Std.U8 32#usize

/-- [libcrux_ml_kem::ind_cca::unpacked::MlKemKeyPairUnpacked]
    Source: 'libcrux-ml-kem/src/ind_cca.rs', lines 491:4-494:5
    Visibility: public -/
structure ind_cca.unpacked.MlKemKeyPairUnpacked (Vector : Type) (K : Std.Usize)
  where
  private_key : ind_cca.unpacked.MlKemPrivateKeyUnpacked Vector K
  public_key : ind_cca.unpacked.MlKemPublicKeyUnpacked Vector K

/-- [libcrux_ml_kem::ind_cca::unpacked::transpose_a::closure]
    Source: 'libcrux-ml-kem/src/ind_cca.rs', lines 827:28-827:86 -/
@[reducible]
def ind_cca.unpacked.transpose_a.closure (Vector : Type) (K : Std.Usize) :=
Unit

/-- [libcrux_ml_kem::ind_cca::unpacked::transpose_a::closure::closure]
    Source: 'libcrux-ml-kem/src/ind_cca.rs', lines 827:41-827:85 -/
@[reducible]
def ind_cca.unpacked.transpose_a.closure.closure (Vector : Type) (K :
  Std.Usize) :=
Unit

/-- [libcrux_ml_kem::RandomnessError]
    Source: 'libcrux-ml-kem/src/lib.rs', lines 80:0-80:27
    Visibility: public -/
@[reducible]
def RandomnessError := Unit

/-- [libcrux_ml_kem::mlkem512::MlKem512]
    Source: 'libcrux-ml-kem/src/mlkem512.rs', lines 30:0-30:20
    Visibility: public -/
@[reducible]
def mlkem512.MlKem512 := Unit

/-- [libcrux_ml_kem::mlkem768::MlKem768]
    Source: 'libcrux-ml-kem/src/mlkem768.rs', lines 37:0-37:20
    Visibility: public -/
@[reducible]
def mlkem768.MlKem768 := Unit

/-- [libcrux_ml_kem::mlkem1024::MlKem1024]
    Source: 'libcrux-ml-kem/src/mlkem1024.rs', lines 29:0-29:21
    Visibility: public -/
@[reducible]
def mlkem1024.MlKem1024 := Unit

/-- [libcrux_ml_kem::mlkem1024::rand::generate_key_pair::closure]
    Source: 'libcrux-ml-kem/src/mlkem1024.rs', lines 589:21-589:40 -/
@[reducible]
def mlkem1024.rand.generate_key_pair.closure (T0 : Type) (Clause0_Clause0_Error
  : Type) :=
Unit

/-- [libcrux_ml_kem::mlkem1024::rand::encapsulate::closure]
    Source: 'libcrux-ml-kem/src/mlkem1024.rs', lines 608:21-608:40 -/
@[reducible]
def mlkem1024.rand.encapsulate.closure (T0 : Type) (Clause0_Clause0_Error :
  Type) :=
Unit

/-- [libcrux_ml_kem::mlkem512::rand::generate_key_pair::closure]
    Source: 'libcrux-ml-kem/src/mlkem512.rs', lines 579:21-579:40 -/
@[reducible]
def mlkem512.rand.generate_key_pair.closure (T0 : Type) (Clause0_Clause0_Error
  : Type) :=
Unit

/-- [libcrux_ml_kem::mlkem512::rand::encapsulate::closure]
    Source: 'libcrux-ml-kem/src/mlkem512.rs', lines 598:21-598:40 -/
@[reducible]
def mlkem512.rand.encapsulate.closure (T0 : Type) (Clause0_Clause0_Error :
  Type) :=
Unit

/-- [libcrux_ml_kem::mlkem768::rand::generate_key_pair::closure]
    Source: 'libcrux-ml-kem/src/mlkem768.rs', lines 562:21-562:40 -/
@[reducible]
def mlkem768.rand.generate_key_pair.closure (T0 : Type) (Clause0_Clause0_Error
  : Type) :=
Unit

/-- [libcrux_ml_kem::mlkem768::rand::encapsulate::closure]
    Source: 'libcrux-ml-kem/src/mlkem768.rs', lines 581:21-581:40 -/
@[reducible]
def mlkem768.rand.encapsulate.closure (T0 : Type) (Clause0_Clause0_Error :
  Type) :=
Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::decaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 150:29-150:88 -/
@[reducible]
def mlkem512.KemMlKem512.decaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::decaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 147:29-147:89 -/
@[reducible]
def mlkem512.KemMlKem512.decaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::decaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 144:29-144:91 -/
@[reducible]
def mlkem512.KemMlKem512.decaps.closure := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::encaps::closure#3]
    Source: 'traits/src/kem/slice.rs', lines 135:29-135:89 -/
@[reducible]
def mlkem512.KemMlKem512.encaps.closure_3 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::encaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 132:29-132:88 -/
@[reducible]
def mlkem512.KemMlKem512.encaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::encaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 129:29-129:91 -/
@[reducible]
def mlkem512.KemMlKem512.encaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::encaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 126:29-126:89 -/
@[reducible]
def mlkem512.KemMlKem512.encaps.closure := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::keygen::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 118:29-118:89 -/
@[reducible]
def mlkem512.KemMlKem512.keygen.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::keygen::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 115:29-115:88 -/
@[reducible]
def mlkem512.KemMlKem512.keygen.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem512::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem512::MlKem512}::keygen::closure]
    Source: 'traits/src/kem/slice.rs', lines 112:29-112:88 -/
@[reducible]
def mlkem512.KemMlKem512.keygen.closure := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::decaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 150:29-150:88 -/
@[reducible]
def mlkem768.KemMlKem768.decaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::decaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 147:29-147:89 -/
@[reducible]
def mlkem768.KemMlKem768.decaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::decaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 144:29-144:91 -/
@[reducible]
def mlkem768.KemMlKem768.decaps.closure := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::encaps::closure#3]
    Source: 'traits/src/kem/slice.rs', lines 135:29-135:89 -/
@[reducible]
def mlkem768.KemMlKem768.encaps.closure_3 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::encaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 132:29-132:88 -/
@[reducible]
def mlkem768.KemMlKem768.encaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::encaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 129:29-129:91 -/
@[reducible]
def mlkem768.KemMlKem768.encaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::encaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 126:29-126:89 -/
@[reducible]
def mlkem768.KemMlKem768.encaps.closure := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::keygen::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 118:29-118:89 -/
@[reducible]
def mlkem768.KemMlKem768.keygen.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::keygen::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 115:29-115:88 -/
@[reducible]
def mlkem768.KemMlKem768.keygen.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem768::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem768::MlKem768}::keygen::closure]
    Source: 'traits/src/kem/slice.rs', lines 112:29-112:88 -/
@[reducible]
def mlkem768.KemMlKem768.keygen.closure := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::decaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 150:29-150:88 -/
@[reducible]
def mlkem1024.KemMlKem1024.decaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::decaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 147:29-147:89 -/
@[reducible]
def mlkem1024.KemMlKem1024.decaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::decaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 144:29-144:91 -/
@[reducible]
def mlkem1024.KemMlKem1024.decaps.closure := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::encaps::closure#3]
    Source: 'traits/src/kem/slice.rs', lines 135:29-135:89 -/
@[reducible]
def mlkem1024.KemMlKem1024.encaps.closure_3 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::encaps::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 132:29-132:88 -/
@[reducible]
def mlkem1024.KemMlKem1024.encaps.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::encaps::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 129:29-129:91 -/
@[reducible]
def mlkem1024.KemMlKem1024.encaps.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::encaps::closure]
    Source: 'traits/src/kem/slice.rs', lines 126:29-126:89 -/
@[reducible]
def mlkem1024.KemMlKem1024.encaps.closure := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::keygen::closure#2]
    Source: 'traits/src/kem/slice.rs', lines 118:29-118:89 -/
@[reducible]
def mlkem1024.KemMlKem1024.keygen.closure_2 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::keygen::closure#1]
    Source: 'traits/src/kem/slice.rs', lines 115:29-115:88 -/
@[reducible]
def mlkem1024.KemMlKem1024.keygen.closure_1 := Unit

/-- [libcrux_ml_kem::mlkem1024::{impl libcrux_traits::kem::slice::Kem for libcrux_ml_kem::mlkem1024::MlKem1024}::keygen::closure]
    Source: 'traits/src/kem/slice.rs', lines 112:29-112:88 -/
@[reducible]
def mlkem1024.KemMlKem1024.keygen.closure := Unit

end MlKem
