// GENERATED by scripts/build_corpus.py from aeneas/tests/src/bool-cmp.rs
//! Regression test: comparison operators ([<], [<=], [>=], [>]) applied to
//! booleans.

pub fn le(a: bool, b: bool) -> bool {
    a <= b
}

pub fn lt(a: bool, b: bool) -> bool {
    a < b
}

pub fn ge(a: bool, b: bool) -> bool {
    a >= b
}

pub fn gt(a: bool, b: bool) -> bool {
    a > b
}
