// GENERATED by scripts/build_corpus.py from aeneas/tests/src/bst/src/bst.rs
//! Adapted from https://github.com/RaitoBezarius/avl-verification

pub enum Ordering {
    Less,
    Equal,
    Greater,
}

trait Ord {
    fn cmp(&self, other: &Self) -> Ordering;
}

struct Node<T> {
    value: T,
    left: Tree<T>,
    right: Tree<T>,
}

type Tree<T> = Option<Box<Node<T>>>;

struct TreeSet<T> {
    root: Tree<T>,
}

impl<T: Ord> TreeSet<T> {
    pub fn new() -> Self {
        Self { root: None }
    }

    pub fn find(&self, value: T) -> bool {
        let mut current_tree = &self.root;

        while let Some(current_node) = current_tree {
            match current_node.value.cmp(&value) {
                Ordering::Less => current_tree = &current_node.right,
                Ordering::Equal => return true,
                Ordering::Greater => current_tree = &current_node.left,
            }
        }

        false
    }
    pub fn insert(&mut self, value: T) -> bool {
        let mut current_tree = &mut self.root;

        while let Some(current_node) = current_tree {
            match current_node.value.cmp(&value) {
                Ordering::Less => current_tree = &mut current_node.right,
                Ordering::Equal => return false,
                Ordering::Greater => current_tree = &mut current_node.left,
            }
        }

        *current_tree = Some(Box::new(Node {
            value,
            left: None,
            right: None,
        }));

        true
    }
}
