// GENERATED by scripts/build_corpus.py from aeneas/tests/src/issue-charon-1172.rs

#[derive(Default)]
pub struct Key {
    round_keys: [[u8; 16]; 29],
}

pub fn new() {
    let _ = Key::default();
}
