// GENERATED by scripts/build_corpus.py from aeneas/tests/src/issue-440-type-error.rs

enum PeanoNum {
    Zero,
    Succ(Box<PeanoNum>),
}

fn f(x: &mut PeanoNum, value: isize) {
    match x {
        PeanoNum::Zero => {
            std::mem::replace(x, PeanoNum::Succ(Box::new(PeanoNum::Zero)));
        }
        PeanoNum::Succ { .. } => {}
    }
}
