// GENERATED by scripts/build_corpus.py — edit scripts/corpus_manifest.tsv instead.
// Crate-level attributes are the union of those in the included test files.
#![feature(box_patterns)]
#![feature(register_tool)]
#![register_tool(aeneas)]
#![register_tool(charon)]
#![allow(unused, dead_code, non_camel_case_types, non_snake_case, non_upper_case_globals, unused_parens, unused_assignments, unreachable_code, private_bounds, private_interfaces, unused_mut, clippy::all)]

pub mod adt_borrows;
pub mod adt;
pub mod array_slice_index;
pub mod arrays;
pub mod arrays_defs;
pub mod as_mut;
pub mod assert_cfg;
pub mod bitwise;
pub mod blanket_impl;
pub mod bool_cmp;
pub mod cast_signed;
pub mod const_shadow;
pub mod constants;
pub mod curve25519;
pub mod default;
pub mod defaulted_method;
pub mod demo;
pub mod deref;
pub mod discriminant;
pub mod drop;
pub mod dynamic_size;
pub mod from_to;
pub mod generic_unit_output;
pub mod hashmap;
pub mod higher_ranked_trait_bounds;
pub mod into;
pub mod issue_1044_opaque_tuple;
pub mod issue_1141_impl_fn_ref;
pub mod issue_1250_anonymous_const;
pub mod issue_134_loop_shared_borrows;
pub mod issue_194_recursive_struct_projector;
pub mod issue_270_loop_list;
pub mod issue_440_type_error;
pub mod issue_789_loop_ctx_match;
pub mod issue_801_hrtb;
pub mod issue_803_self_in_array;
pub mod issue_807_missing_symbolic_value;
pub mod issue_815_global_referencing_fallible_global;
pub mod issue_charon_1172;
pub mod iterators_array;
pub mod iterators_scalar;
pub mod join_duplicate;
pub mod joins;
pub mod list_borrows;
pub mod loop_shared_loan_in_join;
pub mod loops_adts;
pub mod loops_issues;
pub mod loops_nested_rec;
pub mod loops_nested;
pub mod loops_rec;
pub mod loops_sequences;
pub mod loops;
pub mod mini_tree;
pub mod names;
pub mod nested_borrows;
pub mod no_nested_borrows;
pub mod options;
pub mod order;
pub mod overflowing_ops;
pub mod paper;
pub mod print;
pub mod range;
pub mod rename_attribute;
pub mod scalars;
pub mod slices;
pub mod static_items;
pub mod switch_test;
pub mod traits;
pub mod vec;
pub mod avl;
pub mod bst;
pub mod tutorial;
pub mod glue;
