// GENERATED by scripts/build_corpus.py from aeneas/tests/src/mini_tree.rs

struct Node {
    child: OptNode,
}

type OptNode = Option<Box<Node>>;

struct Tree {
    root: OptNode,
}

impl Tree {
    pub fn explore(&self) {
        let mut current_tree = &self.root;

        while let Some(current_node) = current_tree {
            current_tree = &current_node.child
        }
    }
}
