// GENERATED by scripts/build_corpus.py from aeneas/tests/src/options.rs

fn test_unwrap_or<T>(x: Option<T>, default: T) -> T {
    x.unwrap_or(default)
}

fn test_expect<T>(x: Option<T>, msg: &str) -> T {
    x.expect(msg)
}

fn test_is_some<T>(x: Option<T>) -> bool {
    x.is_some()
}
