// GENERATED by scripts/build_corpus.py from aeneas/tests/src/switch_test.rs
//^ note: coq gives "invalid notation for pattern"
fn match_u32(x: u32) -> u32 {
    match x {
        0 => 0,
        1 => 1,
        _ => 2,
    }
}
